### ISSUE TITLE
[FEATURE]: Create a new Figma file for sharing brand identity, logo, colors etc

### ISSUE THREAD

**Issue by akshatgoel07** [SyntaxUI/syntaxui#100]
### Feature Description 📝

Uses: 
- Can copy already existing designs to improve upon them.
- Color palette 
- Logo, Fonts

### Motivation 🌟

I was designing thumbnails for components and wanted to know what are the primary and secondary colors used

### Expected Behavior 🤔

Create a Figma file, share its common link in the discord channel.

**Comment by epoll31** [comment]
There is a color palette pinned in the contributors channel on discord

**Comment by Ansub** [comment]
yeah as discussed with @akshatgoel07 i will be creating a figma file, this is a ticket for that

**Comment by epoll31** [comment]
I think it's a great idea, just thought I'd add this in case it was helpful

**Comment by Ansub** [comment]
which idea 🤔

**Comment by epoll31** [comment]
the figma file

**Comment by Ansub** [comment]
yeah figma file is a good idea, will be making a design system too in future in that figma file ✨
