### ISSUE TITLE
[BUG]: `/demo` page should only be accessible in development builds

### ISSUE THREAD

**Issue by epoll31** [SyntaxUI/syntaxui#106]
### Description 📝

We have a demo page that is used to test out components. Right now this is in production at https://syntaxui.com/demo.

We should remove this page from production builds.

### Link 🔗

https://syntaxui.com/demo

### Steps to Reproduce 🔄

1. Go to https://syntaxui.com/demo

### Screenshots 📸

n/a

### Expected Behavior 🤔

The `/demo` page should only exist in development and not in production

### Actual Behavior 😱

The `/demo` page exists in production

### Environment 🌍

n/a

**Comment by Ansub** [comment]
removed in [8b9f5c9](https://github.com/Ansub/SyntaxUI/commit/8b9f5c92c9b0492064d1ac25d76f01b89e46286c)
