### ISSUE TITLE
[BUG]: Button Component Missing Active State 

### ISSUE THREAD

**Issue by shrix1** [SyntaxUI/syntaxui#173]
## There is no active state on button component in sidebar : https://syntaxui.com/components/button/neubrutalism-button

<img width="1438" alt="Screenshot 2024-05-08 at 2 24 10 PM" src="https://github.com/Ansub/SyntaxUI/assets/92677078/fbbc26a9-bba9-4ead-a6d5-bc7902c84113">

## Active state should look something like this:

<img width="287" alt="Screenshot 2024-05-08 at 2 32 50 PM" src="https://github.com/Ansub/SyntaxUI/assets/92677078/773611b1-2c91-4b3d-8700-d5f58309d9f8">

### Link 🔗

https://syntaxui.com/components/button/neubrutalism-button

**Comment by The-CodeINN** [comment]
Are you working on it??

**Comment by epoll31** [comment]
This might be the intended functionality.

But, if we wanted to change it to include the subitems too, we can change `Navigation.tsx`:

> `let isActiveGroup =
    group.links.findIndex((link) => link.href === pathname) !== -1 `

This is how the current tab is selected, we can use `includes` instead of `===` or something like that.
