### ISSUE TITLE
[BUG]: Theme toggle flickering

### ISSUE THREAD

**Issue by The-CodeINN** [SyntaxUI/syntaxui#175]
### Description 📝

When attempting to toggle the theme, the interface experiences rapid flickering, reverting back to the original theme almost immediately. 

Though it is commented out in the code

### Screenshots 📸

![image](https://github.com/Ansub/SyntaxUI/assets/67247138/3caa5b3b-7fa9-4bcc-a9f4-834062beeffc)

**Comment by The-CodeINN** [comment]
I am currently investigating what could be the problem

**Comment by Ansub** [comment]
yeah that's why i commented it out because it was not working and dark mode is not a priority atm. 

But if you want to debug it, feel free to do so, as it will definitely help in the future as Dark Mode is in the roadmap

**Comment by Ansub** [comment]
> Can I work on this?

sure

**Comment by theaniketnegi** [comment]
> > Can I work on this?
> 
> sure

I did end up finding (and probably fixing) what could be causing the theme flickering, but it seems intentional as the dark mode hasn't been implemented yet.

**Comment by Ansub** [comment]
where was the issue, can you lmk the file name?

**Comment by theaniketnegi** [comment]
> where was the issue, can you lmk the file name?

It seems to be present in in the ThemeWatcher component in app/providers.tsx

The specific code snippet: 
`if (resolvedTheme === systemTheme) {
        setTheme('light')
 }`

which seems to force the light theme whenever there's an attempt to change the theme.
