### ISSUE TITLE
[FEATURE]: Add a Glassmorphic button

### ISSUE THREAD

**Issue by vishnuprasad2004** [SyntaxUI/syntaxui#188]
### Feature Description 📝

A Glassmorphism Button (button with glass-like effect)

Tailwind Playground link:  [https://play.tailwindcss.com/Y9Sr11vrVR](https://play.tailwindcss.com/Y9Sr11vrVR)

### Screenshots 📸

In Light Mode
![image](https://github.com/Ansub/SyntaxUI/assets/116942066/1d03776b-978e-4d78-a3ae-e29dce66eeef)
In Dark mode
![image](https://github.com/Ansub/SyntaxUI/assets/116942066/9a51a6a9-0bb4-4491-986b-1b6a10840cc7)

**Comment by epoll31** [comment]
I had also created a Glassmorphism Button for SyntaxUI in the past.

Here is what mine looks like.

https://github.com/Ansub/SyntaxUI/assets/16091805/31a88df8-1122-4d3d-9900-6335e75f7d99

**Comment by Ansub** [comment]
@epoll31 what if we remove that red background at the back

**Comment by epoll31** [comment]
This is what that looks like:
<img width="267" alt="Screenshot 2024-05-13 at 9 53 48 AM" src="https://github.com/Ansub/SyntaxUI/assets/16091805/c8bede53-19d5-4d45-a3ac-3aeb0d073c16">

The red part behind it is what gives it it's glassy look.

**Comment by Ansub** [comment]
hmm, you are right. we can do something similar to this then 

https://codepen.io/tin-fung-hk/pen/MWrRqBw

**Comment by epoll31** [comment]
That's pretty similar to what I had :). Do you want me to make it a square, or rotate the background, or both?

**Comment by Ansub** [comment]
can you raise a PR for the glassmorphism button you made or lmk if it was already there i will re-open it

**Comment by Ansub** [comment]
we actually need that button but looking for a better UI @vishnuprasad2004
