### ISSUE TITLE
[FEATURE]: Add a 4 column responsive Footer

### ISSUE THREAD

**Issue by subhadeeproy3902** [SyntaxUI/syntaxui#197]
### Feature Description 📝

Will have 4 columns and a desc and will be responsive as well. The footer will actually be a professional one

### Screenshots 📸

![image](https://github.com/Ansub/SyntaxUI/assets/111780029/d265b51f-8d74-4433-8936-de203c8e3d04)
![image](https://github.com/Ansub/SyntaxUI/assets/111780029/e052f1d5-9b5f-4517-be89-0f07e4450f85)

**Comment by subhadeeproy3902** [comment]
@Ansub @johnforte @brennerm  please assign me this.

**Comment by Ansub** [comment]
Hey @subhadeeproy3902 assigned it to you.

I was planning on adding this but it was not completely showing up because of the limited width space we have so i am not sure how it will look.

**Comment by subhadeeproy3902** [comment]
> Hey @subhadeeproy3902 assigned it to you.
> 
> I was planning on adding this but it was not completely showing up because of the limited width space we have so i am not sure how it will look.

Sure i will be sending a PR today check it out :)
