### ISSUE TITLE
[FEATURE]: use only tailwind css for Icon Toggle like we do in SimpleToggle

### ISSUE THREAD

**Issue by Ansub** [SyntaxUI/syntaxui#204]
### Feature Description 📝

since we have migrated back to only using Tailwind CSS for SimpleToggle component, we can do the similar thing for IconToggle as that component is basically inherited from SimpleToggle component.

PR for reference: https://github.com/Ansub/SyntaxUI/pull/201

**Comment by shashank6341** [comment]
Hi @Ansub, Can you please assign me on this.

**Comment by Ansub** [comment]
All yours @shashank6341

**Comment by shashank6341** [comment]
Hi @Ansub thanks a lot.

Updated the codebase and created a Pull Request.

**Comment by epoll31** [comment]
@Ansub We should be able to close this now
