### ISSUE TITLE
[FEATURE]:  Add a  responsive Table 

### ISSUE THREAD

**Issue by 0xyosef** [SyntaxUI/syntaxui#207]
### Feature Description 📝

Add customizable and flexible tables and will be responsive as well

### Screenshots 📸

`Desktop`
![table](https://github.com/Ansub/SyntaxUI/assets/82626103/017578bc-a7f7-419e-bf14-96f2d058a225)

`Moble`
![table2](https://github.com/Ansub/SyntaxUI/assets/82626103/df7440ea-9c41-4a1e-b253-c80894574931)

**Comment by 0xyosef** [comment]
@Ansub please assign me this.

**Comment by Ansub** [comment]
@0xyosef I am not looking to add table in SyntaxUI as there are well known libraries like [shadcn](https://ui.shadcn.com/docs/components/table) which are doing it way better  work in this area.
