### ISSUE TITLE
[FEATURE]: Add a Landing Page Component

### ISSUE THREAD

**Issue by tejartr7** [SyntaxUI/syntaxui#228]
### Feature Description 📝

- **Ready to Use:** Easily integrate the landing page into your project with minimal setup.
- **User-Friendly:** Simplifies the process of creating a visually appealing and effective landing page.
- **Customizable:** Tailor the component to fit your specific needs and branding.

- **Light and Dark Mode Support:** The landing page automatically adjusts its color scheme based on the user's system preferences, providing a seamless experience in both light and dark modes.

- **Responsive Design:** Fully responsive and optimized for different screen sizes and devices, ensuring a consistent look and feel across all platforms.

### Screenshots 📸

![image](https://github.com/SyntaxUI/syntaxui/assets/97605400/d6764e0e-707b-4f1e-890d-f02982434a11)
![image](https://github.com/SyntaxUI/syntaxui/assets/97605400/eeea12aa-be59-4dcf-9888-f5826b5e2ee7)

**Comment by epoll31** [comment]
Hey @tejartr7,

Thanks for opening the issue and the PR. However, we don’t really need this specific component in our showcase. If you have any different ideas, we would love to discuss them either in a new GitHub issue or on our Discord. Feel free to reach out on our Discord if you have any questions :)
