### ISSUE TITLE
[BUG]: Better color for Social Icons in Footer

### ISSUE THREAD

**Issue by Ansub** [SyntaxUI/syntaxui#229]
### Description 📝

Right now icons are not clearly visible in dark mode for Footer, we can use a the color with hex code `#fafafa  for this.

### Screenshots 📸

![CleanShot 2024-06-16 at 16 25 39@2x](https://github.com/SyntaxUI/syntaxui/assets/12985873/2a79ab6a-8107-4340-8095-9b1ab72a08a5)

**Comment by thecurioussailor** [comment]
hi there, can you assign me this issue?

**Comment by Ansub** [comment]
@thecurioussailor it’s already done by @RDrohan

**Comment by thecurioussailor** [comment]
> @thecurioussailor it’s already done by @RDrohan
Alright!
