### ISSUE TITLE
[FEATURE]: Gradient Suggestions

### ISSUE THREAD

**Issue by Ansub** [SyntaxUI/syntaxui#234]
### Feature Description 📝

I am seeking suggestions for gradients to enhance the syntax UI. 

If you have any gradient hex-code recommendations, please list them below in the following format for easy integration into the gradient card:

```
bg-gradient-to-r from-[#6ee7b7] via-[#34d399] to-[#10b981]
```

**Comment by faisal004** [comment]
bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-500 to-blue-700

Hi @Ansub  by using the above string  we can have as many gradients we want  ellipse at top or bottom , left ,right and maybe a ellipse or circle  .

**Comment by Ansub** [comment]
This is really neat @faisal004, I added 3 new radial gradients
![CleanShot 2024-07-02 at 17 04 17@2x](https://github.com/SyntaxUI/syntaxui/assets/12985873/d80fb1b5-1b1e-4aa8-82f9-aba46ba2aaf8)

**Comment by faisal004** [comment]
Thanks man
