### ISSUE TITLE
[FEATURE]: Adding more hover animations

### ISSUE THREAD

**Issue by Ansub** [SyntaxUI/syntaxui#235]
### Feature Description 📝

Hover animation section looks empty and requires some love, if you have some nice hover animations in mind, drop that idea below so that it can be added to SyntaxUI 

### Screenshots 📸

![CleanShot 2024-06-19 at 18 31 55@2x](https://github.com/SyntaxUI/syntaxui/assets/12985873/332aefa7-d570-4e3e-8df5-eeec54f2a435)

**Comment by Asin-Junior-Honore** [comment]
hey 👋
@Ansub, could you assign this issue to me

**Comment by Ansub** [comment]
All yours brother, it's a open issue you can create a PR and if rest want to add more they can create a different PR for that :)

**Comment by Asin-Junior-Honore** [comment]
Hey @Ansub 

I’ve created a really nice hover animation for a button component, but I noticed that there are no existing CSS files in the codebase to add my styles. Could I create a new CSS file for my button component, or do you have any other suggestions on how I should proceed?

Thanks!

**Comment by Asin-Junior-Honore** [comment]
hey @Ansub 
please could you please review my pull request please, I have so much hover animations I would  love to add once this my pr gets approved and merged thanks 😊
