### ISSUE TITLE
[FEATURE]: Better Card Image for Banner

### ISSUE THREAD

**Issue by Ansub** [SyntaxUI/syntaxui#252]
### Feature Description 📝

The banner card currently uses a placeholder div component labeled "banner." This can be replaced with an image, as done for other components.

### Screenshots 📸

![CleanShot 2024-07-06 at 14 08 52@2x](https://github.com/SyntaxUI/syntaxui/assets/12985873/31ee10ff-f670-4b8a-a368-fee450900fee)

**Comment by siddhant-agrawal01** [comment]
Can you provide the link to this component? I didn't find it

**Comment by Ansub** [comment]
https://syntaxui.com/blocks/banner

**Comment by Dharsan15** [comment]
But the banner component doesn't look like the screenshot i think it is already updated and what kind of enhancement should we make for the card component

**Comment by Ansub** [comment]
Yeah, I have added that. 

Closing this issue.
