### ISSUE TITLE
[BUG]: Code Highlighter is not working properly.

### ISSUE THREAD

**Issue by Ansub** [SyntaxUI/syntaxui#253]
### Description 📝

The ComponentPreview component is not highlighting the code properly. Below is the image that shows the issue.

### Link 🔗

https://syntaxui.com/blocks/banner

### Screenshots 📸

![CleanShot 2024-07-06 at 14 15 41@2x](https://github.com/SyntaxUI/syntaxui/assets/12985873/d4757bcc-19b5-4b1f-8f21-a112ec940714)

**Comment by epoll31** [comment]
I played around with changing the docs banner file from a ‘tsx‘ to an ‘mdx‘ and that corrected the syntax highlighting. I haven't cleaned it up to open the PR yet, but I believe that this is a clean solution to this issue.
