### ISSUE TITLE
[FEATURE]: Width changes in docs

### ISSUE THREAD

**Issue by Ansub** [SyntaxUI/syntaxui#257]
### Feature Description 📝

We can decrease the width of Sidebar component as this takes a lot of space 
<img width="309" alt="image" src="https://github.com/SyntaxUI/syntaxui/assets/12985873/d8f0a020-b36d-41f1-a936-a15f6cbf126b">

Also components currently takes less space that's why we are not able to add components which have more width. we can increase the width that components will take inside (docs) folder.

<img width="1398" alt="image" src="https://github.com/SyntaxUI/syntaxui/assets/12985873/6098a89d-8b3c-470d-a648-1a477a1891f8">

**Comment by isrark005** [comment]
Hie @Ansub, is there a specific width you have in mind?

I have shift a layout by `32px` here let me know if this looks right?

before 
![image](https://github.com/SyntaxUI/syntaxui/assets/78822488/9bb92502-038a-4f36-8871-d043f97b1019)

After shifting layout by `32px` 
![image](https://github.com/SyntaxUI/syntaxui/assets/78822488/a788d7b2-badd-49c0-9dff-7c6e19335540)

**Comment by Ansub** [comment]
I am sorry but i am not able to find out the different in both images, can you please tell me where to look for it?

**Comment by isrark005** [comment]
The sidebar width 😅
![image](https://github.com/SyntaxUI/syntaxui/assets/78822488/d0707eec-34ac-44cd-ba93-5fa6982dccda)

**Comment by Ansub** [comment]
Yeah, but we also need to increase the width of the right side where all the components are displayed so that it looks more symmetrical.
