### ISSUE TITLE
[BUG]: Skewed Infinite Scroll don't work in dark mode

### ISSUE THREAD

**Issue by SikandarJODD** [SyntaxUI/syntaxui#262]
### Description 📝

Background colors are not suitable in dark mode
- Code includes no dark mode 
![image](https://github.com/user-attachments/assets/c42a588d-d939-49cc-bf34-dc4426c9dccc)
 

### Link 🔗

https://syntaxui.com/animations/skewed-infinite-scroll

### Screenshots 📸

![image](https://github.com/user-attachments/assets/5c773a58-0d10-4129-801e-27d27df08871)
after pasting the code from website

**Comment by SikandarJODD** [comment]
Code in Syntax UI is totally different : 
![image](https://github.com/user-attachments/assets/b1d4b022-9893-4fcd-8644-efd35c96d4b6)

**Comment by Ansub** [comment]
looks like this to me 🤔 
![CleanShot 2024-07-12 at 09 17 21@2x](https://github.com/user-attachments/assets/c28a85d4-b253-44a2-9c10-dda9f2c541a2)

**Comment by SikandarJODD** [comment]
i am trying to say the original code of skewed infinite scroll is different and code in copy component is totally different please update it for dark mode

**Comment by Ansub** [comment]
gotcha, that makes sense i will have a look at that

**Comment by Ansub** [comment]
fixed in c866ff1401620e025622c73e541e308e193b25c9 

Thanks for the bug report!
