### ISSUE TITLE
🐞:  Meta description is not appearing correctly when searching SyntaxUI

### ISSUE THREAD

**Issue by Ansub** [SyntaxUI/syntaxui#55]
**Describe the bug**
on searching SyntaxUI on google, description of each section appears like this which might impact the SEO
![CleanShot 2024-04-22 at 11 16 52@2x](https://github.com/Ansub/SyntaxUI/assets/12985873/bd265619-b39a-4e4e-b73e-5b5515043141)

**Comment by isrark005** [comment]
![image](https://github.com/SyntaxUI/syntaxui/assets/78822488/c9171a9a-9a2e-4cd0-ae98-14dacdbc1744)
I think this is fixed?

**Comment by Ansub** [comment]
yeah i think it's google's indexing issue we are adding meta description from our end hence closing this issue
